name: kana_to_kanji
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.37.6+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  go_router: ^14.2.1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path: ^1.9.0
  stacked: ^3.4.3
  rive: ^0.13.9
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  isar:
    version: ^4.0.3
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: ^4.0.3
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.4
  http: ^1.2.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.2
  feedback: ^3.1.0
  envied: ^0.5.4+1
  github: ^9.24.0
  device_info_plus: ^10.1.0
  image: ^4.2.0
  intl: ^0.19.0
  infinite_scroll_pagination: ^4.0.0
  upgrader: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.7.0
  mockito: ^5.4.2
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/animations/
    - assets/images/
    - assets/images/logos/

  fonts:
    - family: MPlusRounded1c
      fonts:
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Black.ttf
          weight: 900
          style: normal